### ISSUE TITLE
Read Current from INA219 with Arduino UNO/Mega

### ISSUE THREAD

**Issue by ame57** [jvestman/skimibowi#11]
Hi,
I'm quite new to github so pardon me if it's a too general question.
For my project, I'm using an Adafruit INA219 current sensor connected to an Arduino UNO/Mega.
Does part of your code allow this?
Thank you very much for your support

**Comment by jvestman** [comment]
Hi!

This is not probably what you are looking for. Using Adafruit INA219 breakout you should check out Adafruit's documentation. 

Skimibowi is a tool that is used to design printed circuit boards with KiCad. 

Br,
Jussi
